auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Jabari_Bi
url: http://www.itechdog.com
feed: /atom.xml
author_info: <a href="http://www.itechdog.com/">Jabari_Bi</a>
